get http://localhost:3000/api/guest/issues/680dc2ff8fa9cb9657665c19


###
post http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstname": "ramil",
    "lastname": "tacang",
    "email": "NtBZUaq123a4@example.com",
    "password": "12345678"
}